name: Generate Contribution Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: zozomovie
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update contribution snake"
          add: "dist/*.svg"
